#!/bin/bash
# shellcheck disable=SC2206
# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS A TEMPLATE AND IT SHOULD NOT BE DEPLOYED TO PRODUCTION!

#SBATCH --job-name=${JOB_NAME}
#SBATCH --output=${JOBS_DIR}/${JOB_NAME}-%j.out
#SBATCH --account=${ACCOUNT}
#SBATCH --partition=${PARTITION}
#SBATCH --time=${TIME}
${GIVEN_NODE}
### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodes=${NUM_NODES}
#SBATCH --cpus-per-task=${NUM_CPUS}
#SBATCH --mem=${MEMORY}
#SBATCH --ntasks-per-node=${NUM_GPUS_PER_NODE}
#SBATCH --gres=gpu:${NUM_GPUS_PER_NODE}

## Specify the working directory for this job
#SBATCH --chdir=${DIR}

# Load modules or your own conda environment here
# module load pytorch/v1.4.0-gpu

source ~/.bashrc
#${CONDA_PATH}
export WANDB_DISABLE_SERVICE=True
conda activate ${CONDA_ENV}

# ===== Call your code below =====
srun ${COMMAND_PLACEHOLDER}
